### ISSUE TITLE
Perform speedup analysis after Numba/Dask optimization

### ISSUE THREAD

**Issue by rcharit** [WSUCptSCapstone-Fall2022Spring2023/remi-hpcstochpy#40]
- Measure execution times of StochPy for simulation scripts before and after Numba and Dask optimization
- Measure additional metrics between non-optimized StochPy and optimized StochPy as neeed
- Compile this information for later inclusion in the project report, class presentation, and presentation to our sponsor

**Comment by rcharit** [comment]
Moving to Sprint 4, due to being unfinished in Sprint 3

**Comment by MichaelJMcNaughton** [comment]
This objective has been rendered obsolete by direction from the client being to investigate a means of replacing StochPy entirely.
