### ISSUE TITLE
Use Numba to optimize StochPy doStochSim

### ISSUE THREAD

**Issue by rcharit** [WSUCptSCapstone-Fall2022Spring2023/remi-hpcstochpy#44]
- Explore the use of Numba to optimize the doStochSim() function and other functions as necessary (documentation, example code, etc.) COMPLETED
- Implement Numba features into StochPy code OBSOLETE

**Comment by rcharit** [comment]
Moving to Sprint 4, due to being unfinished in Sprint 3

**Comment by MichaelJMcNaughton** [comment]
After investigation into the viability of doing so and a discussion with the client this goal has been rendered obsolete and so is being closed manually.
